image: debian:stretch

variables:
  FINGERPRINT: C7D495254D9CC8ADDC5A60BFDEB64CDBAAC4FDA6
  SLEEP_TIME: 7
  PATCH_FILE: apticron.patch

stages:
  - test
  - artifacts
  - deploy

before_script:
  - apt-get update -q && apt-get install -qy curl apticron gnupg
  - ln -sf $PWD/apticron -t /usr/sbin/
  - ln -sf $PWD/apticron.conf -t /etc/apticron/
  - sed -i '/^EMAIL=/s/root/alfred.j.kwak@ducks.nl/' /etc/apticron/apticron.conf
  - sed -i '/^NOTIFY_NO_UPDATES/c\NOTIFY_NO_UPDATES="1"' /etc/apticron/apticron.conf
  - gpg --batch --import alfreds-keys/alfreds-gpg-key.sec
  - gpg --import alfreds-keys/alfreds-gpg-key.pub

testUnencryptedOutput:
  stage: test
  script:
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsUnencrypted

testMissingPublicKeyOutput:
  stage: test
  script:
    - gpg --batch --yes --delete-secret-keys $FINGERPRINT
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsUnencrypted

testEncryptedOutput:
  stage: test
  script:
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsEncrypted

testUnencryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsUnencrypted

testMissingPublicKeyOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - gpg --batch --yes --delete-secret-keys $FINGERPRINT
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsUnencrypted

testEncryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apticron && sleep $SLEEP_TIME
    - ./test/assertThatMailIsEncrypted

testThatDisablingIsObeyed:
  stage: test
  script:
  - sed -i '/^GPG_ENCRYPT/c\GPG_ENCRYPT="0"' /etc/apticron/apticron.conf
  - apticron && sleep $SLEEP_TIME
  - ./test/assertThatMailIsUnencrypted

testUnencryptedOutputWithCustomFromSetting:
  stage: test
  script:
    - sed -i '/^EMAIL/c\EMAIL="root"' /etc/apticron/apticron.conf
    - sed -i '/# CUSTOM_FROM/c\CUSTOM_FROM="alfred.j.kwak@ducks.nl"' /etc/apticron/apticron.conf
    - apticron && sleep $SLEEP_TIME
    - if grep -qe "From. alfred.j.kwak@ducks.nl" /var/mail/mail; then exit 0; else exit 1; fi

testEncryptedOutputWithCustomFromSetting:
  stage: test
  script:
    - sed -i '/# CUSTOM_FROM/c\CUSTOM_FROM="alfred.j.kwak@ducks.nl"' /etc/apticron/apticron.conf
    - apticron && sleep $SLEEP_TIME
    - if grep -q "alfred.j.kwak@ducks.nl" /var/log/exim4/mainlog; then exit 0; else exit 1; fi

createPatchForDebianRepository:
  stage: artifacts
  before_script:
    - apt-get update -q && apt-get install -qy git
  script:
    - git remote add debian git://git.debian.org/git/collab-maint/apticron.git
    - git fetch debian
    - git diff debian/master HEAD apticron apticron.conf > $PATCH_FILE
  artifacts:
    paths:
      - $PATCH_FILE

uploadPatchToNC:
  only:
    - /^master$/
  image:
    name: tutum/curl:latest
  stage: deploy
  before_script: []
  script:
    - curl -X PUT -u $AB_USER:$AB_PW --data-binary @"$PATCH_FILE" "https://penrose.duckdns.org/nextcloud/public.php/webdav/$PATCH_FILE"
