image: debian:stretch

variables:
  FINGERPRINT: 30CD5E17BDA2FBC3
  SLEEP_TIME: 7
  PATCH_FILE: apticron.patch

stages:
  - test
  - patch-generation
  - deploy

before_script:
  - apt-get update -q && apt-get install -qy curl apticron gnupg
  - gpg --keyserver pgp.mit.edu --receive-keys $FINGERPRINT
  - ln -sf $PWD/apticron.conf -t /etc/apticron/
  - sed -i '/^EMAIL=/s/root/matthias.baumgarten@web.de/' /etc/apticron/apticron.conf
  - sed -i 's/# NOTIFY_NO_UPDATES="0"/NOTIFY_NO_UPDATES="1"/' /etc/apticron/apticron.conf
  - ln -sf $PWD/apticron -t /usr/sbin/

testUnencryptedOutput:
  stage: test
  script:
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testMissingPublicKeyOutput:
  stage: test
  script:
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testEncryptedOutput:
  stage: test
  script:
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsEncrypted

testUnencryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testMissingPublicKeyOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testEncryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsEncrypted

testThatDisablingIsObeyed:
  stage: test
  script:
  - sed -i '/^GPG_ENCRYPT/c\GPG_ENCRYPT="0"' /etc/apticron/apticron.conf
  - apticron && sleep $SLEEP_TIME
  - ./assertThatMailIsUnencrypted

createPatchForDebianRepository:
  stage: patch-generation
  before_script:
    - apt-get update -q && apt-get install -qy git
  script:
    - git remote add debian git://git.debian.org/git/collab-maint/apticron.git
    - git fetch debian
    - git diff debian/master HEAD apticron apticron.conf > $PATCH_FILE
  artifacts:
    paths:
      - $PATCH_FILE

uploadPatchToNC:
  only:
    - /^master$/
  image:
    name: tutum/curl:latest
  stage: deploy
  before_script:
    - curl --version
  script:
    - curl -X PUT -u s5EOQ9XbiXz04jh:$AB_PW --data-binary @"$PATCH_FILE" "https://penrose.duckdns.org/nextcloud/public.php/webdav/$PATCH_FILE"
