image: debian:stretch

variables:
  FINGERPRINT: 30CD5E17BDA2FBC3
  SLEEP_TIME: 7

before_script:
  - apt-get update -q && apt-get install -qy curl apticron gnupg
  - gpg --keyserver pgp.mit.edu --receive-keys $FINGERPRINT
  - sed -i '/^EMAIL=/s/root/matthias.baumgarten@web.de/' /etc/apticron/apticron.conf
  - sed -i 's/# NOTIFY_NO_UPDATES="0"/NOTIFY_NO_UPDATES="1"/' /etc/apticron/apticron.conf
  - ln -sf $PWD/apticron -t /usr/sbin/

testUnencryptedOutput:
  stage: test
  script:
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testMissingPublicKeyOutput:
  stage: test
  script:
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testEncryptedOutput:
  stage: test
  script:
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsEncrypted

testUnencryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apt-get purge -qy gnupg
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testMissingPublicKeyOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - gpg --batch --yes --delete-keys $FINGERPRINT
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsUnencrypted

testEncryptedOutputWithHeirloom:
  stage: test
  script:
    - apt-get update -q && apt-get install -qy heirloom-mailx
    - apticron && sleep $SLEEP_TIME
    - ./assertThatMailIsEncrypted
