#!/bin/bash -eu

BIN_TARGET="/usr/sbin/apticron"
cp apticron $BIN_TARGET
chown root:root $BIN_TARGET
chmod 755 $BIN_TARGET

CONF_TARGET="/etc/apticron/apticron.conf"
cp apticron.conf $CONF_TARGET
chown root:root $CONF_TARGET
chmod 644 $CONF_TARGET
