#!/bin/bash -eu

BIN_TARGET="/usr/sbin/apticron"
cp apticron $BIN_TARGET
chown root:root $BIN_TARGET
chmod 755 $BIN_TARGET

CONF_TARGET="/etc/apticron/apticron.conf"
tail -7 apticron.conf >> $CONF_TARGET
