#!/bin/sh -e

case "$1" in
    purge)
	if test -x /usr/bin/ucf ; then
		/usr/bin/ucf --purge /etc/cron.d/apticron
		/usr/bin/ucf --purge /etc/apticron/apticron.conf
	fi
	rm -f /etc/cron.d/apticron /etc/cron.d/apticron.ucf-*
	rm -f /var/lib/misc/apticron.cron
	rm -f /etc/apticron/apticron.conf*
	if [ -d /etc/apticron ] ; then 
		rmdir /etc/apticron || true
	fi
    ;;
esac

#DEBHELPER#
