#!/bin/sh -e

case "$1" in
    purge)
	ucf --purge /etc/cron.d/apticron
	ucf --purge /etc/apticron/apticron.conf
	rm -f /etc/cron.d/apticron /etc/cron.d/apticron.ucf-*
	rm -f /var/lib/misc/apticron.cron
	rm -f /etc/apticron/apticron.conf*
	if [ -d /etc/apticron ] ; then
		rmdir /etc/apticron || true
	fi
	rm -rf /var/lib/apticron
    ;;
esac

#DEBHELPER#
