#!/bin/sh -e

case "$1" in
    purge)
	if which ucf >/dev/null; then
		ucf --purge /etc/cron.d/apticron
		ucf --purge /etc/apticron/apticron.conf
	fi
	rm -f /etc/cron.d/apticron /etc/cron.d/apticron.ucf-*
	rm -f /var/lib/misc/apticron.cron
	rm -f /etc/apticron/apticron.conf*
	if [ -d /etc/apticron ] ; then
		rmdir /etc/apticron || true
	fi
	rm -rf /var/lib/apticron
    ;;
esac

# Remove cron.daily file which has been installed by old (and bugged)
# apticron versions. (see #587597)
dpkg-maintscript-helper rm_conffile /etc/cron.daily/apticron -- "$@"

#DEBHELPER#
